apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grimoirelab-base
resources:
  - namespace.yaml
  - configmaps.yaml
  - storage.yaml
  - mariadb.yaml
  - valkey.yaml
  - opensearch.yaml
  - opensearch-dashboards.yaml
  - sortinghat.yaml
  - mordred.yaml
  - nginx.yaml
  - netsuite-sync-cronjob.yaml