apiVersion: v1
kind: Secret
metadata:
  name: grimoirelab-secrets
  namespace: grimoirelab
type: Opaque
stringData:
  mysql-root-password: ""
  sortinghat-db-password: ""
  sortinghat-superuser-password: "admin"
  sortinghat-secret-key: "secret"
  opensearch-initial-admin-password: "GrimoireLab.1"

