kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 9000
        protocol: TCP
    extraMounts:
      - hostPath: /tmp/grimoirelab
        containerPath: /tmp/grimoirelab
