apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
  - storage-hostpath.yaml
patches:
  - path: nginx-nodeport.yaml
    target:
      kind: Service
      name: grimoirelab-gateway
  - path: sortinghat-static-pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: sortinghat-static