apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sortinghat-static
  labels:
    app.kubernetes.io/name: grimoirelab
    app.kubernetes.io/component: sortinghat-static
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sortinghat-hostpath
  hostPath:
    path: /tmp/grimoirelab/sortinghat-static
    type: DirectoryOrCreate

